Develop
VNG-Realisatie/Haal-Centraal-BRP-bewoning pull request #87
Opened 2021-01-28 14:50 UTC by JohanBoer

2021-02-01 08:03 UTC, MelvLee approved these changes

2021-02-01 15:10 UTC, fsamwel reviewed
Wat mij betreft is dit deze goed. Maar ik zie dat OAS-lint is gefaald. Controleer je die nog voor je de marge doet?

2021-02-01 15:42 UTC, CathyDingemanse requested changes

2021-02-01 15:42 UTC, CathyDingemanse commented on specificatie/openapi.yaml
> +                        Het aantal keren dat een alleenstaande of een gezin naar het verblijfsobject, de ligplaats of de standplaats is verhuisd binnen de opgegeven periode.
de verblijfplaats ipv het verblijfplaats

2021-02-03 13:52 UTC, JohanBoer reviewed
> Wat mij betreft is dit deze goed. Maar ik zie dat OAS-lint is gefaald. Controleer je die nog voor je de marge doet?

Dat kan ik checken na de merge. Ik heb voor bewoning de actions niet lokaal staan..

2021-02-03 13:52 UTC, JohanBoer commented on specificatie/openapi.yaml
> +                        Het aantal keren dat een alleenstaande of een gezin naar het verblijfsobject, de ligplaats of de standplaats is verhuisd binnen de opgegeven periode.
Op zich is dat correct, maar het gaat hier over een verblijfsobject. Dat is toch wel een het ?

2021-02-03 13:54 UTC, merged