Releasenotes toegevoegd van 0.9.0 naar 1.0.0
VNG-Realisatie/Haal-Centraal-BRP-bewoning pull request #91
Opened 2021-02-22 12:02 UTC by JohanBoer

2021-02-22 13:12 UTC, MelvLee commented on docs/releasenotes.md
> +- datumtotenmet --> datumtotenmet
datumtotenmet --> datumtotenmet  => datumtotenmet --> datumTotEnMet?

2021-02-22 13:16 UTC, MelvLee commented on docs/releasenotes.md
> +- datumtotenmet --> datumtotenmet
datumtotenmet --> datumtotenmet => datumtotenmet --> datumTotEnMet?

2021-02-22 13:18 UTC, MelvLee commented on docs/releasenotes.md
> +- datumtotenmet --> datumtotenmet
datumtotenmet --> datumtotenmet => datumtotenmet --> datumTotEnMet?

2021-02-22 13:20 UTC, MelvLee commented on docs/releasenotes.md
> +- IngeschrevenPersoon_Links --> IngeschrevenPersoon_Links
IngeschrevenPersoon_Links --> IngeschrevenPersoon_Links => IngeschrevenPersoon_Links --> IngeschrevenPersoonLinks?

2021-02-22 13:46 UTC, fsamwel commented on docs/releasenotes.md
> +- Zoeken op nummeraanduding (parameter identificatiecodenummeraanduiding) is vervallen en zoek op adresseerbaarobject (parameter adresseerbaarObjectIdentificatie) is toegevoegd
@CathyDingemanse @MelvLee @JohanBoer waarom hebben we eigenlijk niet de zoekmogelijkheid op nummeraanduiding behouden en alleen zoeken op adoId toegevoegd?

2021-02-22 13:47 UTC, fsamwel commented on docs/releasenotes.md
> +- Zoeken op nummeraanduding (parameter identificatiecodenummeraanduiding) is vervallen en zoek op adresseerbaarobject (parameter adresseerbaarObjectIdentificatie) is toegevoegd
is dit niet hetzelfde als regel 29?

2021-02-22 13:51 UTC, fsamwel commented on docs/releasenotes.md
> +- Zoeken op nummeraanduding (parameter identificatiecodenummeraanduiding) is vervallen en zoek op adresseerbaarobject (parameter adresseerbaarObjectIdentificatie) is toegevoegd
nummeraanduding --> nummeraanduiding

2021-02-22 13:51 UTC, fsamwel commented on docs/releasenotes.md
> +- Zoeken op nummeraanduding (parameter identificatiecodenummeraanduiding) is vervallen en zoek op adresseerbaarobject (parameter adresseerbaarObjectIdentificatie) is toegevoegd
op deze plek is de term "zoeken op" denk ik niet correct. Het gaat om het raadplegen van de bewoning op een adresseerbaar object (was: raadplegen van de bewoning op een adres).

Is het niet handig eerst de algemene grootste wijziging te beschrijven: de uri van resource bewoning wordt opgebouwd op basis van adoId i.p.v. op numId.

2021-02-22 13:55 UTC, fsamwel commented on docs/releasenotes.md
> +- Verblijfplaats is aangepast door hergebruik van het BAG-adres
consequenties hiervan? naamOpenbareRuimte --> straat, enz.

2021-02-22 13:56 UTC, fsamwel commented on docs/releasenotes.md
> +- Bewoning_links.nummeraanduiding --> BewoningLinks.nummeraanduidingen
en dit is een array geworden

2021-02-22 13:57 UTC, fsamwel commented on docs/releasenotes.md
> +- IngeschrevenPersoon.nationaliteit --> IngeschrevenPersoon.nationaliteiten
algemeen: definitie embedded ingeschreven persoon gewijzigd, zie release notes BRP bevragen?

2021-02-22 13:57 UTC, fsamwel commented on docs/releasenotes.md
> +VerblijfplaatsInOnderzoek.naamOpenbarerRuimte --> VerblijfplaatsInOnderzoek.straatnaam
streepje (opsomming)

2021-02-22 13:58 UTC, fsamwel commented on docs/releasenotes.md
> +- IngeschrevenPersoon_Links --> IngeschrevenPersoon_Links
is de wijziging van een componentnaam breaking?

2021-02-22 14:00 UTC, fsamwel commented on docs/releasenotes.md
> +  - NaamPersoon.regelVoorafgaandAanAanschrijfwijze toegevoegd
hoort dit bij "Enkele namen van schema-componenten zijn aangepast..."?

2021-02-22 14:00 UTC, fsamwel requested changes
zie opmerkingen

2021-02-22 17:44 UTC, JohanBoer commented on docs/releasenotes.md
> +- datumtotenmet --> datumtotenmet
Aangepast

2021-02-22 17:44 UTC, JohanBoer commented on docs/releasenotes.md
> +- datumtotenmet --> datumtotenmet
Aangepast

2021-02-22 17:44 UTC, JohanBoer commented on docs/releasenotes.md
> +- datumtotenmet --> datumtotenmet
Aangepast

2021-02-22 17:46 UTC, JohanBoer commented on docs/releasenotes.md
> +- IngeschrevenPersoon_Links --> IngeschrevenPersoon_Links
Aangepast (Allebei de opmerkingen)

2021-02-22 18:12 UTC, JohanBoer commented on docs/releasenotes.md
> +- Zoeken op nummeraanduding (parameter identificatiecodenummeraanduiding) is vervallen en zoek op adresseerbaarobject (parameter adresseerbaarObjectIdentificatie) is toegevoegd
> @CathyDingemanse @MelvLee @JohanBoer waarom hebben we eigenlijk niet de zoekmogelijkheid op nummeraanduiding behouden en alleen zoeken op adoId toegevoegd?

Dit is in #8 besproken. Ik weet niet waarom we niet alsnog de nummeraanduidingIdentificatie als Query-parameter hebben toegevoegd, maar de wijzigingen als gevolg heb ik redelijk expliciet voorgesteld. 
@fsamwel @CathyDingemanse : Gaan we hier nog een discussie over voeren ? Zo ja dan wacht ik met release 1.0.0.

2021-02-22 18:16 UTC, JohanBoer commented on docs/releasenotes.md
> +- Zoeken op nummeraanduding (parameter identificatiecodenummeraanduiding) is vervallen en zoek op adresseerbaarobject (parameter adresseerbaarObjectIdentificatie) is toegevoegd
> op deze plek is de term "zoeken op" denk ik niet correct. Het gaat om het raadplegen van de bewoning op een adresseerbaar object (was: raadplegen van de bewoning op een adres).
> 
> Is het niet handig eerst de algemene grootste wijziging te beschrijven: de resource bewoningen is de bewoning van een adresseerbaar object (was: bewoning van een adres). Gevolg: de uri van resource bewoningen wordt opgebouwd op basis van adoId i.p.v. op numId.

Aangepast

2021-02-22 18:17 UTC, JohanBoer commented on docs/releasenotes.md
> +- Zoeken op nummeraanduding (parameter identificatiecodenummeraanduiding) is vervallen en zoek op adresseerbaarobject (parameter adresseerbaarObjectIdentificatie) is toegevoegd
Het zijn 2 verschillende endpoints (Bewoning en Verloop).

2021-02-22 18:28 UTC, JohanBoer commented on docs/releasenotes.md
> +  - NaamPersoon.regelVoorafgaandAanAanschrijfwijze toegevoegd
Aangepast

2021-02-22 18:28 UTC, JohanBoer commented on docs/releasenotes.md
> +VerblijfplaatsInOnderzoek.naamOpenbarerRuimte --> VerblijfplaatsInOnderzoek.straatnaam
Aangepast

2021-02-22 18:51 UTC, JohanBoer commented on docs/releasenotes.md
> +- Verblijfplaats is aangepast door hergebruik van het BAG-adres
Volgens mij heb ik die allemaal opgenomen. Ik zal ze verplaatsen en als sub-punten onder deze opmerking zetten.

2021-02-22 18:53 UTC, JohanBoer commented on docs/releasenotes.md
> +- Bewoning_links.nummeraanduiding --> BewoningLinks.nummeraanduidingen
Aangepast

2021-02-22 18:58 UTC, JohanBoer commented on docs/releasenotes.md
> +- IngeschrevenPersoon.nationaliteit --> IngeschrevenPersoon.nationaliteiten
Volgens mij heb ik alle individueel relevante wijziginge opgenomen. Ik heb de genereervarianten van 0.9.0 en 1.0.0 vergelijken. Dat is denk ik prettiger voor een developer dan verwijzen naar de releasnotes van een andere API.

2021-02-23 07:52 UTC, MelvLee commented on docs/releasenotes.md
> +  - Hal-componenten die alleen _links bevatten zijn omgenoemd van xxxHal naar xxxHalBasi
xxxHalBasi => xxxHalBasis?

2021-02-23 09:42 UTC, JohanBoer commented on docs/releasenotes.md
> +  - Hal-componenten die alleen _links bevatten zijn omgenoemd van xxxHal naar xxxHalBasi
Slip of the keyboard... Aangepast

2021-02-23 09:50 UTC, fsamwel approved these changes

2021-02-23 14:31 UTC, merged